num_to_name = {
	1: 'imp_type_conv',
	2: 'evaluate_diff_sidewise',
	3: 'bitwise_op',
	4: 'assignments_in_conditions',
	5: 'comparing_floats',
	6: 'gvar_as_fnpar',
	7: 'check_init',
	8: 'goto_continue',
	9: 'allocs',
	10: 'recursion',
	11: 'comments_style',
	12: 'code_commented',
	13: 'seq_in_comment',
	14: 'identifiers_scoping',
	15: 'proto_decl',
	16: 'sizeof_effects',
	17: 'rhshift_limits',
	18: 'unarymin_on_unsigned',
	19: 'loop_iterator',
	20: 'else_check',
	21: 'pointer_levels',
	22: 'unions',
	23: 'unreachable',
	24: 'default_check',
	25: 'booleans_switch',
}